"""
Django settings for growth_skool project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# BASE_URL = "https://dispatchskool.com/" # For production use
BASE_URL = 'http://127.0.0.1:8000/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+9qyu0$!3np#mzlsgluumdww4^dg0+@wpn8@^r*ni9cu)e47z#'
ENCRYPT_KEY = b'0T8rrQtvapiIr6znitchWIAkX-nZE8K3qLq2AGasHpM='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# In Production, this MUST be ['*'] to let custom domains hit the middleware
ALLOWED_HOSTS = ['*']

# New setting: The actual domains your app runs on
SYSTEM_DOMAINS = [
    'localhost',
    '127.0.0.1',
    'dispatchskool.com',
    'whitelabel.dispatchskool.com',
]

AUTH_USER_MODEL = "users.CustomUser"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

		'main.apps.MainConfig',
		'users.apps.UsersConfig',
		'subscriptions.apps.SubscriptionsConfig',
		'leads_data.apps.LeadsDataConfig',
		'dashboard.apps.DashboardConfig',
    'affiliates.apps.AffiliatesConfig',
    'warmup.apps.WarmupConfig',
    'new_warmup.apps.NewWarmupConfig',
    'drip_campaigns.apps.DripCampaignsConfig',
    'unibox.apps.UniboxConfig',

		'widget_tweaks',
		'django_ckeditor_5',
    'django_celery_beat',
    'django_celery_results'
]


# Celery Configuration
CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC' # Keep this consistent with your Django TIME_ZONE
CELERY_TASK_TRACK_STARTED = True # Useful for monitoring task states
CELERY_TASK_CREATE_DIRS = False # Prevent Celery from creating directories for logs if you're not using file logging for tasks

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


customColorPalette = [
        {
            'color': 'hsl(207, 90%, 54%)',
            'label': 'Blue'
        },
    ]

CKEDITOR_5_ALLOW_ALL_FILE_TYPES = True
CKEDITOR_5_UPLOAD_FILE_TYPES = [
    'pdf', 'doc', 'docx', 'txt', 'csv', 'xls', 'xlsx',
    'jpg', 'jpeg', 'png', 'gif', 'zip'
]
CKEDITOR_5_UPLOAD_PATH = 'ckeditor_uploads/' 
CK_EDITOR_5_UPLOAD_FILE_VIEW_NAME = "custom_ckeditor_upload"

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": {
            "items": [
                "heading", "|", "bold", "italic", "underline", "strikethrough",
                "highlight", "|", "link", "uploadImage", "fileUpload",
                "bulletedList", "numberedList", "todoList", "outdent", "indent", "|",
                "fontSize", "fontFamily", "fontColor", "fontBackgroundColor",
                "removeFormat", "insertTable",
            ],
            "shouldNotGroupWhenFull": True,
        },
        "image": {
            "toolbar": [
                "imageTextAlternative", "|",
                "imageStyle:alignLeft", "imageStyle:block", "imageStyle:alignRight"
            ],
            "upload": {"url": "/ckeditor5/image_upload/"},
        },
        "fileUpload": {
            "upload": {"url": "/ckeditor5/file_upload/"},
        },
        "link": {
            "decorators": {
                "isDownloadable": {
                    "mode": "manual",
                    "label": "Downloadable",
                    "attributes": {"download": "file"},
                }
            }
        },
    }
}


MAINTENANCE_MODE = False


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'main.middleware.MaintenanceModeMiddleware',
    'main.middleware.CustomDomainTrackingMiddleware',
]

# Uncomment the following code to enable email + OTP login functionality for future use. Not required now as. Business decision.

# AUTHENTICATION_BACKENDS = [
#     'users.backends.EmailModelBackend',
#     'django.contrib.auth.backends.ModelBackend',
# ]


import os

ROOT_URLCONF = 'growth_skool.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, ('templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'growth_skool.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.postgresql_psycopg2',
       'NAME': 'growht_skool_4',
       'USER': 'postgres',
       'PASSWORD': '1234',
       'HOST': 'localhost',
       'PORT': '5432',
   }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.hostinger.com'
EMAIL_USE_TLS = False  # Enable TLS
EMAIL_USE_SSL = True  # Disable SSL
EMAIL_PORT = 465  # TLS requires port 587
EMAIL_HOST_USER = "info@dispatchskool.com"
EMAIL_HOST_PASSWORD = "Ahmad@2134"

DEFAULT_FROM_EMAIL = "info@dispatchskool.com"

MAILS_SO_API_KEY = '504cfd68-d818-4259-8f31-01c6dbcf47ab'

LOGGING = {
    "version": 1,
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "django_email.log",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


LOGIN_REDIRECT_URL = 'dashboard:index'
LOGIN_URL = 'users:login'
LOGOUT_REDIRECT_URL = 'main:index'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
